# Generated by Django 3.2.11 on 2022-02-06 23:39

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this recipe on the homepage?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
    ]
