# Generated by Django 3.2.11 on 2022-02-07 00:05

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220206_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, help_text='Ingredient list', size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, help_text='Directions list', size=None, verbose_name='Directions'),
        ),
    ]
