# Generated by Django 3.2.11 on 2022-02-07 00:34

import dehy.appz.recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=dehy.appz.recipes.models.upload_to_slug),
        ),
    ]
