# Generated by Django 3.2.11 on 2022-01-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20220125_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'ordering': ['price']},
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
    ]
