# Generated by Django 3.2.11 on 2022-02-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_message_messageuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoQuestionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_source', models.CharField(choices=[('b_r', 'Bar or Restaurant'), ('h', 'Home'), ('o', 'Other')], default='b_r', help_text='Is this for home or commercial use?', max_length=3, verbose_name='')),
                ('response', models.CharField(help_text='What is the name of your Bar/Restaurant/Business?', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='', help_text='message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='visionstatement',
            name='description',
            field=models.TextField(default='', help_text='Description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='visionstatement',
            name='title',
            field=models.CharField(default='', help_text='Vision name', max_length=50, verbose_name='Title'),
        ),
    ]
