# Generated by Django 3.2.11 on 2022-02-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20220227_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfoquestionaire',
            old_name='purchase_source',
            new_name='purchase_business_type',
        ),
    ]
