# Generated by Django 3.2.11 on 2022-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_rename_purchase_source_additionalinfoquestionaire_purchase_business_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfoquestionaire',
            old_name='response',
            new_name='business_name',
        ),
        migrations.AlterField(
            model_name='additionalinfoquestionaire',
            name='purchase_business_type',
            field=models.CharField(choices=[('b_r', 'Bar or Restaurant'), ('h', 'Home'), ('o', 'Other')], default='b_r', help_text='Is this for home or commercial use?', max_length=3, verbose_name='Business or Home'),
        ),
    ]
