# Generated by Django 3.2.12 on 2022-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0008_rename_additionalinfoquestionaire_additionalinfoquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedexAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=450, verbose_name='Token')),
                ('expires_in', models.IntegerField(default=0, help_text='Seconds', verbose_name='Expires in')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('scope', models.CharField(default='', max_length=20, verbose_name='Scope')),
            ],
        ),
    ]
