# Generated by Django 3.2.12 on 2022-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0010_alter_fedexauthtoken_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedexauthtoken',
            name='access_token',
            field=models.CharField(default='', max_length=1000, verbose_name='Token'),
        ),
    ]
