# Generated by Django 3.2.12 on 2022-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0012_alter_fedexauthtoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedexauthtoken',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
