# Generated by Django 3.2.11 on 2022-01-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20220125_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, default=None, help_text='inches', null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, default=None, help_text='inches', null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=None, help_text='lbs', null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, default=None, help_text='inches', null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Leave blank to copy product description', null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Leave blank to copy product title', max_length=255, null=True, verbose_name='Meta title'),
        ),
    ]
