# Generated by Django 3.2.11 on 2022-01-26 21:41

from django.db import migrations
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20220125_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
