# Generated by Django 3.2.11 on 2022-01-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
    ]
