# Generated by Django 3.2.11 on 2022-01-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='parent',
        ),
    ]
