# Generated by Django 3.2.11 on 2022-02-13 05:09

import dehy.appz.catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20220129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to=dehy.appz.catalogue.models.get_image_upload_path, verbose_name='Original'),
        ),
    ]
