# Generated by Django 3.2.11 on 2022-02-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_abstractbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractBase',
        ),
    ]
