# Generated by Django 3.2.11 on 2022-02-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20220227_1702'),
        ('order', '0012_auto_20220218_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_info_questionaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generic.additionalinfoquestionaire'),
        ),
    ]
