# Generated by Django 3.2.11 on 2022-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_additional_info_questionaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='additional_info_questionaire',
            new_name='additional_info_questionnaire',
        ),
    ]
