# Generated by Django 3.2.11 on 2022-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20220125_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment Intent ID', max_length=100, null=True),
        ),
    ]
