# Generated by Django 3.2.12 on 2022-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20220402_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='price_incl_tax',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Price incl. Tax'),
        ),
    ]
