# Generated by Django 3.2.11 on 2022-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_basket_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment Intent ID(Stripe)', max_length=100, null=True),
        ),
    ]
