# Generated by Django 3.2.12 on 2022-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20220301_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='stripe_order_id',
            field=models.CharField(blank=True, help_text='Stripe Order ID', max_length=120, null=True),
        ),
    ]
