# Generated by Django 3.2.12 on 2022-03-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_basket_stripe_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='stripe_order_status',
            field=models.CharField(blank=True, help_text='Stripe Order Status', max_length=50, null=True),
        ),
    ]
