# Generated by Django 3.2.12 on 2022-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_basket_stripe_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='payment_intent_client_secret',
            field=models.CharField(blank=True, help_text='Payment Intent Client Secret(Stripe)', max_length=150, null=True),
        ),
    ]
