name: dehy

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  start:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: # with clean required if using virtual env, otherwise the venv is deleted every time
        clean: false

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        instance-ids: ${{ secrets.INSTANCE_ID }}
        comment: Deploy the staging branch
        working-directory: /home/admin/dehy/dehy
        command: /bin/sh source deploy.sh


        # Catch SSM outputs
    - name: Get the outputs
      run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
