name: dehy

on:
  push:
    branches: [staging]
  # pull_request:
  #   branches: [staging]

jobs:
  start:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-access-key-id: AKIATWP3CLBXHB3BA7JO
        aws-secret-access-key: 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
        aws-region: us-east-2
        instance-ids:
          'i-029d22a511f603dbd'
        # comment: Deploy the staging branch
        working-directory: /home/admin/dehy
        command: /bin/sh ./deploy.sh

        # Catch SSM outputs
    - name: Get the outputs
      run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
